package vn.com.vti.springexam.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import vn.com.vti.springexam.entity.JobType;
import vn.com.vti.springexam.entity.JobTypeExample;

public interface JobTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_type
     *
     * @mbg.generated Mon Mar 27 21:17:49 JST 2023
     */
    long countByExample(JobTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_type
     *
     * @mbg.generated Mon Mar 27 21:17:49 JST 2023
     */
    int deleteByExample(JobTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_type
     *
     * @mbg.generated Mon Mar 27 21:17:49 JST 2023
     */
    int deleteByPrimaryKey(String jobTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_type
     *
     * @mbg.generated Mon Mar 27 21:17:49 JST 2023
     */
    int insert(JobType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_type
     *
     * @mbg.generated Mon Mar 27 21:17:49 JST 2023
     */
    int insertSelective(JobType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_type
     *
     * @mbg.generated Mon Mar 27 21:17:49 JST 2023
     */
    List<JobType> selectByExample(JobTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_type
     *
     * @mbg.generated Mon Mar 27 21:17:49 JST 2023
     */
    JobType selectByPrimaryKey(String jobTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_type
     *
     * @mbg.generated Mon Mar 27 21:17:49 JST 2023
     */
    int updateByExampleSelective(@Param("record") JobType record, @Param("example") JobTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_type
     *
     * @mbg.generated Mon Mar 27 21:17:49 JST 2023
     */
    int updateByExample(@Param("record") JobType record, @Param("example") JobTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_type
     *
     * @mbg.generated Mon Mar 27 21:17:49 JST 2023
     */
    int updateByPrimaryKeySelective(JobType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_type
     *
     * @mbg.generated Mon Mar 27 21:17:49 JST 2023
     */
    int updateByPrimaryKey(JobType record);
}