package vn.com.vti.springexam.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import vn.com.vti.springexam.entity.Section8;
import vn.com.vti.springexam.entity.Section8Example;

public interface Section8Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section8
     *
     * @mbg.generated Sat Mar 25 16:12:51 JST 2023
     */
    long countByExample(Section8Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section8
     *
     * @mbg.generated Sat Mar 25 16:12:51 JST 2023
     */
    int deleteByExample(Section8Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section8
     *
     * @mbg.generated Sat Mar 25 16:12:51 JST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section8
     *
     * @mbg.generated Sat Mar 25 16:12:51 JST 2023
     */
    int insert(Section8 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section8
     *
     * @mbg.generated Sat Mar 25 16:12:51 JST 2023
     */
    int insertSelective(Section8 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section8
     *
     * @mbg.generated Sat Mar 25 16:12:51 JST 2023
     */
    List<Section8> selectByExample(Section8Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section8
     *
     * @mbg.generated Sat Mar 25 16:12:51 JST 2023
     */
    Section8 selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section8
     *
     * @mbg.generated Sat Mar 25 16:12:51 JST 2023
     */
    int updateByExampleSelective(@Param("record") Section8 record, @Param("example") Section8Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section8
     *
     * @mbg.generated Sat Mar 25 16:12:51 JST 2023
     */
    int updateByExample(@Param("record") Section8 record, @Param("example") Section8Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section8
     *
     * @mbg.generated Sat Mar 25 16:12:51 JST 2023
     */
    int updateByPrimaryKeySelective(Section8 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section8
     *
     * @mbg.generated Sat Mar 25 16:12:51 JST 2023
     */
    int updateByPrimaryKey(Section8 record);
}