package vn.com.vti.springexam.entity;

import java.util.Date;

public class JoinedTable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column joined_table.book_id
     *
     * @mbg.generated Tue Mar 28 15:43:44 JST 2023
     */
    private String bookId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column joined_table.book_name
     *
     * @mbg.generated Tue Mar 28 15:43:44 JST 2023
     */
    private String bookName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column joined_table.price
     *
     * @mbg.generated Tue Mar 28 15:43:44 JST 2023
     */
    private Integer price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column joined_table.discount
     *
     * @mbg.generated Tue Mar 28 15:43:44 JST 2023
     */
    private Integer discount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column joined_table.page_count
     *
     * @mbg.generated Tue Mar 28 15:43:44 JST 2023
     */
    private Integer pageCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column joined_table.isbn13
     *
     * @mbg.generated Tue Mar 28 15:43:44 JST 2023
     */
    private String isbn13;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column joined_table.on_sale_date
     *
     * @mbg.generated Tue Mar 28 15:43:44 JST 2023
     */
    private Date onSaleDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column joined_table.category_name
     *
     * @mbg.generated Tue Mar 28 15:43:44 JST 2023
     */
    private String categoryName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column joined_table.publisher_name
     *
     * @mbg.generated Tue Mar 28 15:43:44 JST 2023
     */
    private String publisherName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column joined_table.book_id
     *
     * @return the value of joined_table.book_id
     *
     * @mbg.generated Tue Mar 28 15:43:44 JST 2023
     */
    public String getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column joined_table.book_id
     *
     * @param bookId the value for joined_table.book_id
     *
     * @mbg.generated Tue Mar 28 15:43:44 JST 2023
     */
    public void setBookId(String bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column joined_table.book_name
     *
     * @return the value of joined_table.book_name
     *
     * @mbg.generated Tue Mar 28 15:43:44 JST 2023
     */
    public String getBookName() {
        return bookName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column joined_table.book_name
     *
     * @param bookName the value for joined_table.book_name
     *
     * @mbg.generated Tue Mar 28 15:43:44 JST 2023
     */
    public void setBookName(String bookName) {
        this.bookName = bookName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column joined_table.price
     *
     * @return the value of joined_table.price
     *
     * @mbg.generated Tue Mar 28 15:43:44 JST 2023
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column joined_table.price
     *
     * @param price the value for joined_table.price
     *
     * @mbg.generated Tue Mar 28 15:43:44 JST 2023
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column joined_table.discount
     *
     * @return the value of joined_table.discount
     *
     * @mbg.generated Tue Mar 28 15:43:44 JST 2023
     */
    public Integer getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column joined_table.discount
     *
     * @param discount the value for joined_table.discount
     *
     * @mbg.generated Tue Mar 28 15:43:44 JST 2023
     */
    public void setDiscount(Integer discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column joined_table.page_count
     *
     * @return the value of joined_table.page_count
     *
     * @mbg.generated Tue Mar 28 15:43:44 JST 2023
     */
    public Integer getPageCount() {
        return pageCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column joined_table.page_count
     *
     * @param pageCount the value for joined_table.page_count
     *
     * @mbg.generated Tue Mar 28 15:43:44 JST 2023
     */
    public void setPageCount(Integer pageCount) {
        this.pageCount = pageCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column joined_table.isbn13
     *
     * @return the value of joined_table.isbn13
     *
     * @mbg.generated Tue Mar 28 15:43:44 JST 2023
     */
    public String getIsbn13() {
        return isbn13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column joined_table.isbn13
     *
     * @param isbn13 the value for joined_table.isbn13
     *
     * @mbg.generated Tue Mar 28 15:43:44 JST 2023
     */
    public void setIsbn13(String isbn13) {
        this.isbn13 = isbn13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column joined_table.on_sale_date
     *
     * @return the value of joined_table.on_sale_date
     *
     * @mbg.generated Tue Mar 28 15:43:44 JST 2023
     */
    public Date getOnSaleDate() {
        return onSaleDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column joined_table.on_sale_date
     *
     * @param onSaleDate the value for joined_table.on_sale_date
     *
     * @mbg.generated Tue Mar 28 15:43:44 JST 2023
     */
    public void setOnSaleDate(Date onSaleDate) {
        this.onSaleDate = onSaleDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column joined_table.category_name
     *
     * @return the value of joined_table.category_name
     *
     * @mbg.generated Tue Mar 28 15:43:44 JST 2023
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column joined_table.category_name
     *
     * @param categoryName the value for joined_table.category_name
     *
     * @mbg.generated Tue Mar 28 15:43:44 JST 2023
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column joined_table.publisher_name
     *
     * @return the value of joined_table.publisher_name
     *
     * @mbg.generated Tue Mar 28 15:43:44 JST 2023
     */
    public String getPublisherName() {
        return publisherName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column joined_table.publisher_name
     *
     * @param publisherName the value for joined_table.publisher_name
     *
     * @mbg.generated Tue Mar 28 15:43:44 JST 2023
     */
    public void setPublisherName(String publisherName) {
        this.publisherName = publisherName;
    }
}