package vn.com.vti.springexam.entity;

import java.util.Date;

public class Member {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.member_id
     *
     * @mbg.generated Sun Mar 26 22:02:55 JST 2023
     */
    private String memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.password
     *
     * @mbg.generated Sun Mar 26 22:02:55 JST 2023
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.last_name
     *
     * @mbg.generated Sun Mar 26 22:02:55 JST 2023
     */
    private String lastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.first_name
     *
     * @mbg.generated Sun Mar 26 22:02:55 JST 2023
     */
    private String firstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.post_code
     *
     * @mbg.generated Sun Mar 26 22:02:55 JST 2023
     */
    private String postCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.address
     *
     * @mbg.generated Sun Mar 26 22:02:55 JST 2023
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.birthday
     *
     * @mbg.generated Sun Mar 26 22:02:55 JST 2023
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.tel_no
     *
     * @mbg.generated Sun Mar 26 22:02:55 JST 2023
     */
    private String telNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.mail_address
     *
     * @mbg.generated Sun Mar 26 22:02:55 JST 2023
     */
    private String mailAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.regist_datetime
     *
     * @mbg.generated Sun Mar 26 22:02:55 JST 2023
     */
    private Date registDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.member_type
     *
     * @mbg.generated Sun Mar 26 22:02:55 JST 2023
     */
    private String memberType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.blood_type
     *
     * @mbg.generated Sun Mar 26 22:02:55 JST 2023
     */
    private String bloodType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.business_type_id
     *
     * @mbg.generated Sun Mar 26 22:02:55 JST 2023
     */
    private String businessTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.job_type_id
     *
     * @mbg.generated Sun Mar 26 22:02:55 JST 2023
     */
    private String jobTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.child_name1
     *
     * @mbg.generated Sun Mar 26 22:02:55 JST 2023
     */
    private String childName1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.child_name2
     *
     * @mbg.generated Sun Mar 26 22:02:55 JST 2023
     */
    private String childName2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.child_name3
     *
     * @mbg.generated Sun Mar 26 22:02:55 JST 2023
     */
    private String childName3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.member_id
     *
     * @return the value of member.member_id
     *
     * @mbg.generated Sun Mar 26 22:02:55 JST 2023
     */
    public String getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.member_id
     *
     * @param memberId the value for member.member_id
     *
     * @mbg.generated Sun Mar 26 22:02:55 JST 2023
     */
    public void setMemberId(String memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.password
     *
     * @return the value of member.password
     *
     * @mbg.generated Sun Mar 26 22:02:55 JST 2023
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.password
     *
     * @param password the value for member.password
     *
     * @mbg.generated Sun Mar 26 22:02:55 JST 2023
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.last_name
     *
     * @return the value of member.last_name
     *
     * @mbg.generated Sun Mar 26 22:02:55 JST 2023
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.last_name
     *
     * @param lastName the value for member.last_name
     *
     * @mbg.generated Sun Mar 26 22:02:55 JST 2023
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.first_name
     *
     * @return the value of member.first_name
     *
     * @mbg.generated Sun Mar 26 22:02:55 JST 2023
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.first_name
     *
     * @param firstName the value for member.first_name
     *
     * @mbg.generated Sun Mar 26 22:02:55 JST 2023
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.post_code
     *
     * @return the value of member.post_code
     *
     * @mbg.generated Sun Mar 26 22:02:55 JST 2023
     */
    public String getPostCode() {
        return postCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.post_code
     *
     * @param postCode the value for member.post_code
     *
     * @mbg.generated Sun Mar 26 22:02:55 JST 2023
     */
    public void setPostCode(String postCode) {
        this.postCode = postCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.address
     *
     * @return the value of member.address
     *
     * @mbg.generated Sun Mar 26 22:02:55 JST 2023
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.address
     *
     * @param address the value for member.address
     *
     * @mbg.generated Sun Mar 26 22:02:55 JST 2023
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.birthday
     *
     * @return the value of member.birthday
     *
     * @mbg.generated Sun Mar 26 22:02:55 JST 2023
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.birthday
     *
     * @param birthday the value for member.birthday
     *
     * @mbg.generated Sun Mar 26 22:02:55 JST 2023
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.tel_no
     *
     * @return the value of member.tel_no
     *
     * @mbg.generated Sun Mar 26 22:02:55 JST 2023
     */
    public String getTelNo() {
        return telNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.tel_no
     *
     * @param telNo the value for member.tel_no
     *
     * @mbg.generated Sun Mar 26 22:02:55 JST 2023
     */
    public void setTelNo(String telNo) {
        this.telNo = telNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.mail_address
     *
     * @return the value of member.mail_address
     *
     * @mbg.generated Sun Mar 26 22:02:55 JST 2023
     */
    public String getMailAddress() {
        return mailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.mail_address
     *
     * @param mailAddress the value for member.mail_address
     *
     * @mbg.generated Sun Mar 26 22:02:55 JST 2023
     */
    public void setMailAddress(String mailAddress) {
        this.mailAddress = mailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.regist_datetime
     *
     * @return the value of member.regist_datetime
     *
     * @mbg.generated Sun Mar 26 22:02:55 JST 2023
     */
    public Date getRegistDatetime() {
        return registDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.regist_datetime
     *
     * @param registDatetime the value for member.regist_datetime
     *
     * @mbg.generated Sun Mar 26 22:02:55 JST 2023
     */
    public void setRegistDatetime(Date registDatetime) {
        this.registDatetime = registDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.member_type
     *
     * @return the value of member.member_type
     *
     * @mbg.generated Sun Mar 26 22:02:55 JST 2023
     */
    public String getMemberType() {
        return memberType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.member_type
     *
     * @param memberType the value for member.member_type
     *
     * @mbg.generated Sun Mar 26 22:02:55 JST 2023
     */
    public void setMemberType(String memberType) {
        this.memberType = memberType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.blood_type
     *
     * @return the value of member.blood_type
     *
     * @mbg.generated Sun Mar 26 22:02:55 JST 2023
     */
    public String getBloodType() {
        return bloodType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.blood_type
     *
     * @param bloodType the value for member.blood_type
     *
     * @mbg.generated Sun Mar 26 22:02:55 JST 2023
     */
    public void setBloodType(String bloodType) {
        this.bloodType = bloodType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.business_type_id
     *
     * @return the value of member.business_type_id
     *
     * @mbg.generated Sun Mar 26 22:02:55 JST 2023
     */
    public String getBusinessTypeId() {
        return businessTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.business_type_id
     *
     * @param businessTypeId the value for member.business_type_id
     *
     * @mbg.generated Sun Mar 26 22:02:55 JST 2023
     */
    public void setBusinessTypeId(String businessTypeId) {
        this.businessTypeId = businessTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.job_type_id
     *
     * @return the value of member.job_type_id
     *
     * @mbg.generated Sun Mar 26 22:02:55 JST 2023
     */
    public String getJobTypeId() {
        return jobTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.job_type_id
     *
     * @param jobTypeId the value for member.job_type_id
     *
     * @mbg.generated Sun Mar 26 22:02:55 JST 2023
     */
    public void setJobTypeId(String jobTypeId) {
        this.jobTypeId = jobTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.child_name1
     *
     * @return the value of member.child_name1
     *
     * @mbg.generated Sun Mar 26 22:02:55 JST 2023
     */
    public String getChildName1() {
        return childName1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.child_name1
     *
     * @param childName1 the value for member.child_name1
     *
     * @mbg.generated Sun Mar 26 22:02:55 JST 2023
     */
    public void setChildName1(String childName1) {
        this.childName1 = childName1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.child_name2
     *
     * @return the value of member.child_name2
     *
     * @mbg.generated Sun Mar 26 22:02:55 JST 2023
     */
    public String getChildName2() {
        return childName2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.child_name2
     *
     * @param childName2 the value for member.child_name2
     *
     * @mbg.generated Sun Mar 26 22:02:55 JST 2023
     */
    public void setChildName2(String childName2) {
        this.childName2 = childName2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.child_name3
     *
     * @return the value of member.child_name3
     *
     * @mbg.generated Sun Mar 26 22:02:55 JST 2023
     */
    public String getChildName3() {
        return childName3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.child_name3
     *
     * @param childName3 the value for member.child_name3
     *
     * @mbg.generated Sun Mar 26 22:02:55 JST 2023
     */
    public void setChildName3(String childName3) {
        this.childName3 = childName3;
    }
}